apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
        - name: task2-app
          image: ghcr.io/${{ secrets.GIT_USER }}/$IMAGE:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 700m
            limits:
              cpu: 700m
---
apiVersion: v1
kind: Service
metadata:
  name: task2-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: task2